"""create_v1_tables

Revision ID: a4c43ccbbf2f
Revises: 4f4cc324a08d
Create Date: 2026-08-13 11:09:35.682288
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c43ccbbf2f'
down_revision = '4f4cc324a08d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('given_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('orcid', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors'))
    )
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collections.id'], name=op.f('fk_collections_parent_id_collections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', 'parent_id', name='uq_collections_name_parent_id')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.Text(), nullable=True),
    sa.Column('volume', sa.Text(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('pages', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('publisher_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('pdf_original_name', sa.Text(), nullable=False),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('reading_status', sa.Enum('INBOX', 'TO_READ', 'READING', 'READ', name='reading_status'), server_default='INBOX', nullable=False),
    sa.Column('rating', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name=op.f('ck_papers_rating_between_0_and_5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers'))
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index('uq_tags_name_lower', 'tags', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SUMMARY', 'INTERPRETATION', 'RESEARCH_RELATION', 'QUESTION', 'IDEA', name='note_type'), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_notes_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes')),
    sa.UniqueConstraint('paper_id', 'type', name='uq_notes_paper_id_type')
    )
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_paper_authors_author_id_authors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_authors_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'author_id', name=op.f('pk_paper_authors')),
    sa.UniqueConstraint('paper_id', 'position', name='uq_paper_authors_paper_id_position')
    )
    op.create_table('paper_collections',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_paper_collections_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_collections_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'collection_id', name=op.f('pk_paper_collections'))
    )
    op.create_table('paper_tags',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_tags_paper_id_papers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_paper_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'tag_id', name=op.f('pk_paper_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_tags')
    op.drop_table('paper_collections')
    op.drop_table('paper_authors')
    op.drop_table('notes')
    op.drop_table('users')
    op.drop_index('uq_tags_name_lower', table_name='tags')
    op.drop_table('tags')
    op.drop_table('papers')
    op.drop_table('collections')
    op.drop_table('authors')
    # ### end Alembic commands ###
